name: Canary releases

on:
  pull_request:
    branches:
      - master

jobs:
  publish-canary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Prepare git
        run: |
          git config --global user.name "Docusaurus Canary"
          git config --global user.email "canary@docusaurus.io"
          git fetch
          git checkout slorber/fix-canary-release
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
          cat .npmrc
          echo "TEST WHOAMI"
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Installation
        run: yarn
      - name: Publish Canary release
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
          npm whoami
          yarn canary
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
